defaults:
  - vpsde_is_config
  - sampler: vpsde_velocity_sampler
  - diffusion: base_temporal_unet
  - likelihood: base_likelihood
  - example: multivariate_gaussian_example
  - _self_

example:
  d: 2
  mu: [[-1.1815],
       [ 0.3824]]
  sigma: [[ 6.0969,  0.3034],
          [ 0.3034,  9.8621]]
