defaults:
  - vpsde_sample_config
  - sampler: vpsde_velocity_sampler
  - diffusion: base_temporal_unet
  - likelihood: base_likelihood
  - example: gaussian_example
  - _self_

example:
  d: 4
  mu: [[-0.3455],
       [-0.4335],
       [-0.6610],
       [ 0.0711]]
  sigma: [[2.1980, 0.9729, 1.0282, 1.6457],
          [0.9729, 0.5591, 0.3118, 0.8382],
          [1.0282, 0.3118, 0.7965, 0.5634],
          [1.6457, 0.8382, 0.5634, 1.5497]]
