defaults:
  - vpsde_sample_config
  - sampler: vpsde_velocity_sampler
  - diffusion: base_temporal_unet
  - likelihood: base_likelihood
  - example: gaussian_example
  - _self_

example:
  d: 4
  mu: [[-0.3455],
       [-0.4335],
       [-0.6610],
       [ 0.0711]]
  sigma: [[ 2.2933,  0.1308, -0.4452,  1.0140],
          [ 0.6580,  3.7737,  0.0101, -0.7439],
          [ 0.2418,  0.2451,  0.2326, -0.3518],
          [ 0.9435, -0.2727,  1.1345,  0.5199]]
